In [1]:
import pandas as pd
import numpy as np

https://www.geeksforgeeks.org/selecting-rows-in-pandas-dataframe-based-on-conditions/

1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
x = np.arange(2, 10)
df = pd.Series(x)
df

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int64

In [3]:
df_list = df.to_list()
df_list

[2, 3, 4, 5, 6, 7, 8, 9]

3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [4]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
add = s1+s2
sub = s1-s2
mult = s1*s2
div = s1/s2

print(s1==s2)
print(s1>s2)
print(s1<s2)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


5. Write a Pandas program to convert a dictionary to a Pandas series.
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [5]:
dct = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
df = pd.Series(dct, dtype=float)
df

a    100.0
b    200.0
c    300.0
d    400.0
e    800.0
dtype: float64

8. Write a Pandas program to convert the first column of a DataFrame as a Series.

In [6]:
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(d)
s = pd.Series(df.col1)
print(type(s))

<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.

In [7]:
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print(s1)
a = s1.values
print(a)
print(type(a))


0       100
1       200
2    python
3    300.12
4       400
dtype: object
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


In [8]:
s1 = pd.Series(['100', '200', '100', '300', '400'])
d = s1.to_numpy(dtype ='int64')
d

array([100, 200, 100, 300, 400])

*** 10. Write a Pandas program to convert Series of lists to one Series.

In [9]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])

ss = s.apply(pd.Series).stack().reset_index(drop=True)
ss

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

11. Write a Pandas program to sort a given Series.

In [10]:
print(ss.sort_values())

4     Black
1     Green
0       Red
3       Red
2     White
5    Yellow
dtype: object


12. Write a Pandas program to add some data to an existing Series.

In [11]:
new_ss = pd.concat([ss, pd.Series([500, "php"])], ignore_index=True)
new_ss

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
6       500
7       php
dtype: object

*** 13. Write a Pandas program to create a subset of a given series based on value and condition.

In [12]:
ss = pd.Series([i for i in range(10)])
sub_ss = ss[ss<5]
sub_ss

0    0
1    1
2    2
3    3
4    4
dtype: int64

14. Write a Pandas program to change the order of index of a given series.

In [13]:
import random
new_sub_ss = sub_ss.reindex([3,4,1,0,2])
new_sub_ss

3    3
4    4
1    1
0    0
2    2
dtype: int64

15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [14]:
print(new_sub_ss.mean())
print(new_sub_ss.std())

2.0
1.5811388300841898


*** 16. Write a Pandas program to get the items of a given series not present in another given series.

In [15]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
result = sr1[~sr1.isin(sr2)]
print(result)


0    1
2    3
4    5
dtype: int64


*** 17. Write a Pandas program to get the items which are not common of two given series. 

In [16]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))
result = sr11[~sr11.isin(sr22)]
print(result)


0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [17]:
sr1 = pd.Series([1, 2, 3, 4, 5])
print(sr1.describe())

result = np.percentile(sr1, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

Minimum, 25th percentile, median, 75th, and maximum of a given series:
[1. 2. 3. 4. 5.]


*** 20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.

In [18]:
num_series = pd.Series(np.random.randint(1, 5, [15]))
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)
print('Disply Mode: ')
display(num_series.mode())


0     Other
1     Other
2     Other
3         1
4         1
5     Other
6     Other
7         1
8     Other
9         1
10    Other
11        1
12    Other
13    Other
14    Other
dtype: object
Disply Mode: 


0    Other
dtype: object

*** 21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series. 

In [19]:
sr = pd.Series([5,15,3,10,25,5,26,1,8,5,2])
result = np.where(sr % 5==0)
print(result)

(array([0, 1, 3, 4, 5, 9]),)


*** 22. Write a Pandas program to extract items at given positions of a given series.

In [20]:
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [0, 2, 6, 11, 21]
result = num_series.take(element_pos)
display(result)

0     2
2     9
6     8
11    0
21    3
dtype: object

*** 23. Write a Pandas program to get the positions of items of a given series in another given series. 

In [21]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
result = [pd.Index(series1).get_loc(i) for i in series2]
print("Positions of items of series2 in series1:")
print(result)


Positions of items of series2 in series1:
[0, 2, 4, 6, 9]


*** 24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series. 

In [22]:
series1 = pd.Series(['php', 'python', 'java', 'c#'])
result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print("\nFirst and last character of each word to upper case:")
print(result)



First and last character of each word to upper case:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


*** 26. Write a Pandas program to compute difference of differences between  numbers of a given series.

In [23]:
series1 = pd.Series([2,3,6,7,4])

print(series1.diff().tolist())
print(series1.diff().diff().tolist())

[nan, 1.0, 3.0, 1.0, -3.0]
[nan, nan, 2.0, -2.0, -4.0]


28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

In [24]:
from dateutil.parser import parse
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
date_series = date_series.map(lambda x: parse(x))
print("Day of month:")
print(date_series.dt.day.tolist())
print("Day of year:")
print(date_series.dt.dayofyear.tolist())
print("Week number:")
print(date_series.dt.weekofyear.tolist())
# print("Day of week:")
# print(date_series.dt.weekday_name.tolist())

Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]


/tmp/ipykernel_68371/2899157629.py:9: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print(date_series.dt.weekofyear.tolist())


29. Write a Pandas program to convert year-month string to dates adding a specified day of the month. 

In [25]:
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
result = date_series.map(lambda d: parse('11' + d))
print(result)


0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


*** 30. Write a Pandas program to filter words from a given series that contain atleast two vowels.

In [26]:
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
result =color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])


1     Green
2    Orange
4    Yellow
5     White
dtype: object


31. Write a Pandas program to compute the Euclidean distance between two given series.

In [27]:
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])

print(np.linalg.norm(x-y))


16.492422502470642


*** 32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [28]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("\nPositions of the values surrounded by smaller values on both sides:")
temp = np.diff(np.sign(np.diff(nums)))
result = np.where(temp == -2)[0] + 1
print(result)



Positions of the values surrounded by smaller values on both sides:
[1 4 8]


*** 33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

In [29]:
str1 = 'abc def abcdef icd'
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
print(element_freq)
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ', current_freq))
print(result)


c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
dtype: int64
abcidefiabcdefiicd


*** 34. Write a Pandas program to compute the autocorrelations of a given numeric series.

In [30]:
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]
print("\nAutocorrelations of the said series:")
print(autocorrelations[1:])



Autocorrelations of the said series:
[-0.12, 0.02, -0.57, -0.33, 0.2, 0.4, 0.07, 0.39, -0.89, 0.05]


*** 35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

In [31]:
result = pd.Series(pd.date_range('2023-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2019:")
print(result)


All Sundays of 2019:
0    2023-01-01
1    2023-01-08
2    2023-01-15
3    2023-01-22
4    2023-01-29
5    2023-02-05
6    2023-02-12
7    2023-02-19
8    2023-02-26
9    2023-03-05
10   2023-03-12
11   2023-03-19
12   2023-03-26
13   2023-04-02
14   2023-04-09
15   2023-04-16
16   2023-04-23
17   2023-04-30
18   2023-05-07
19   2023-05-14
20   2023-05-21
21   2023-05-28
22   2023-06-04
23   2023-06-11
24   2023-06-18
25   2023-06-25
26   2023-07-02
27   2023-07-09
28   2023-07-16
29   2023-07-23
30   2023-07-30
31   2023-08-06
32   2023-08-13
33   2023-08-20
34   2023-08-27
35   2023-09-03
36   2023-09-10
37   2023-09-17
38   2023-09-24
39   2023-10-01
40   2023-10-08
41   2023-10-15
42   2023-10-22
43   2023-10-29
44   2023-11-05
45   2023-11-12
46   2023-11-19
47   2023-11-26
48   2023-12-03
49   2023-12-10
50   2023-12-17
51   2023-12-24
dtype: datetime64[ns]


36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

In [32]:
char_list = list('ABCDEFGHIJKLMNOP')
num_ser = pd.Series(char_list)
df = num_ser.to_frame().reset_index()
print(df.head())


   index  0
0      0  A
1      1  B
2      2  C
3      3  D
4      4  E


37. Write a Pandas program to stack two given series vertically and horizontally.

In [33]:
series1 = pd.Series(range(10))
series2 = pd.Series(list('pqrstuvwxy'))

series1.append(series2)
df = pd.concat([series1, series2], axis=1)
print("\nStack two given series vertically and horizontally:")
print(df)



Stack two given series vertically and horizontally:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


/tmp/ipykernel_68371/3588445279.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  series1.append(series2)


*** 39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.

In [34]:
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print('Smallest: ',nums.idxmin())
print('Largest: ',nums.idxmax())

Smallest:  9
Largest:  4


*** 40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series. 

In [35]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 

print("\nCheck for inequality of the said series & dataframe:")
print(df_data.ne(sr_data, axis = 0))



Check for inequality of the said series & dataframe:
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
