In [1]:
import numpy as np

4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11

In [2]:
arr = np.zeros(10)
arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [3]:
# array with 1 on the border and 0 inside
arr_ones = np.ones((5,5))
arr_ones[1:-1, 1:-1] = 0
display(arr_ones)

# array with 0 on the border and 1 inside
arr_zeros = np.zeros((5,5))
arr_zeros[1:-1, 1:-1] = 1
print(arr_zeros)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


*** 10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

Checkerboard pattern:


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [5]:
lst = [0, 1, 0, 1, 0, 1, 0, 1]
print(lst[::2])

[0, 0, 0, 0]


12. Write a NumPy program to append values to the end of an array.

In [6]:
x = [10, 20, 30]

x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)


# 25. Write a NumPy program to construct an array by repeating
a = [1, 2, 3, 4]
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
Repeating 2 times
[1 2 3 4 1 2 3 4]


13. Write a NumPy program to create an empty and full array.

In [7]:
print('Create an empty array: ')
x = np.empty((3,4))
print(x)
print('Create a full array: ')
y = np.full((3,3),6)
print(y)

Create an empty array: 
[[4.68685133e-310 0.00000000e+000 1.01855798e-312 9.54898106e-313]
 [1.10343781e-312 1.01855798e-312 1.23075756e-312 1.16709769e-312]
 [1.08221785e-312 9.76118064e-313 1.18831764e-312 1.90979621e-312]]
Create a full array: 
[[6 6 6]
 [6 6 6]
 [6 6 6]]


14. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees.

In [8]:
fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:")
print(np.round((5*F/9 - 5*32/9),2))


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [9]:
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])

print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)


Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


16. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.

In [10]:
x = np.array([1,2,3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [11]:
array1 = np.array([2, 10, 20, 40, 60])
array2 = [2, 40]
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

print("Unique elements of the above array:")
x = np.array([10, 10, 20, 20, 30, 30])
print(np.unique(x))

Compare each element of array1 and array2
[ True False False  True False]
Common values between two arrays:
[ 2 40]
Unique values in array1 that are not in array2:
[10 20 60]
Unique values that are in only one (not both) of the input arrays:
[10 20 60]
Unique sorted array of values that are in either of the two input arrays:
[ 2 10 20 40 60]
Unique elements of the above array:
[10 20 30]


26.Write a NumPy program to repeat array elements.

In [12]:
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))


[3 3 3 3]
[1 1 2 2 3 3 4 4]


27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Maximum Values:  5
Minimum Values:  0


28. Write a NumPy program to compare two arrays using NumPy.

In [14]:
a = np.array([1, 2])
b = np.array([4, 5])

print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


30. Write a NumPy program to sort pairs of a first name and a last name and return their indices (first by last name, then by first name).

In [15]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [16]:
x = np.array([[0, 10, 20], [20, 30, 40]])

print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


*** 42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [17]:
x = np.eye(3, dtype=np.int64)
print(x)
print('diagonal equals [4, 5, 6, 8] and zeros elsewhere.: ')
y =  np.diagflat([4, 5, 6, 8])
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
diagonal equals [4, 5, 6, 8] and zeros elsewhere.: 
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


47. Write a NumPy program to create an array like the one below.

48. Write a NumPy program to create an array like the one below.

In [18]:
x = np.tri(4, 3, -1)
print(x)

y = np.triu(np.arange(2, 14).reshape(4, 3), -1)
print(y)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


50. Write a NumPy program to find the 4th element of a specified array.

In [19]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
e1 = x.flat[3]
print("Forth e1ement of the array: ", e1)

[[ 2  4  6]
 [ 6  8 10]]
Forth e1ement of the array:  6


51. Write a NumPy program to change two array axes.

In [20]:
x = np.array([[1,2,3]])
print(x)
y =  np.swapaxes(x,0,1)
print(y)


[[1 2 3]]
[[1]
 [2]
 [3]]


57. Write a NumPy program to remove single-dimensional entries from a specified shape.

In [21]:
x = np.zeros((2, 1, 2))
print(x)
print(np.squeeze(x))


[[[0. 0.]]

 [[0. 0.]]]
[[0. 0.]
 [0. 0.]]


169. Write a NumPy program to get all 2D diagonals of a 3D NumPy array.

In [22]:
np_array = np.arange(3*4*5).reshape(3,4,5)
print("Original Numpy array:")
print(np_array)
result = np.diagonal(np_array, axis1=1, axis2=2)
print("\n2D diagonals: ")
print(result)

Original Numpy array:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

2D diagonals: 
[[ 0  6 12 18]
 [20 26 32 38]
 [40 46 52 58]]


15. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [23]:
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


10. Write a NumPy program to find a matrix or vector norm.

In [24]:
v = np.arange(7)
print(v)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
print(m)
print(type(m))
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)


[0 1 2 3 4 5 6]
Vector norm:
9.539392014169456
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
Matrix norm:
5.477225575051661


3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

In [25]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height']))


Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


7. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

In [26]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


13. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

In [27]:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 

print("Number of occurrences of each value in array: ")
print(np.bincount(array1))


Number of occurrences of each value in array: 
[1 3 2 0 1 0 1 1]


In [28]:
import time
import numpy as np 
SIZE = 200000 
list1 = range(SIZE)
list2 = range(SIZE)
arra1 = np.arange(SIZE)
arra2 = np.arange(SIZE)
start_list = time.time()
result=[(x,y) for x,y in zip(list1,list2)]
print("Time to aggregates elements from each of the iterables:")
print("List:")
print((time.time()-start_list)*1000)
start_array = time.time()
result = arra1 + arra2
print("NumPy array:")
print((time.time()-start_array)*1000)


Time to aggregates elements from each of the iterables:
List:
90.52896499633789
NumPy array:
11.113643646240234
